# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "PyConf Hyderabad 2017"
email: "contact@hydpy.org"
description: "Hyderabad Python Conference 2017"
baseurl: "/women"
url: "http://pyconf.hydpy.org/"
#permalink: "/blog/:title"
googleAnalyticsTrackingId: ""
googleAnalyticsSiteUrl: ""
siteVerification: ""

# Organizer Info
organizerName: "Hyderabad Python User Group"
organizerAlternateName: "HydPy"
organizerDescription: "Hyderabad Python Users Group"
organizerEmail: "hydpy@python.org"
organizerLogo: "/img/seo/pyconf-poster.png"
organizerLink: "http://hydpy.org"

# Head
metaKeywords: "event, python, pycon, pyconf, programming, hyderabad, developers, conference"
twitterAccount: "@hydPython"
socialImageSrcGooglePlus: "/img/seo/pyconf-poster.png"
socialImageSrcTwitter: "/img/seo/pyconf-poster.png"
socialImageSrcFacebook: "/img/seo/pyconf-poster.png"

# Documents
c4pUrl: "https://pyconfhyd.talkfunnel.com/2017/"
c4sponsorsUrl: "/assets/pyconfhyd_prospectus.pdf"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}

 - {permalink: "/schedule/", text: "Schedule"}

 - {permalink: "/speakers/", text: "Speakers"}
 - {permalink: "/about/", text: "About"}

 - {permalink: "/faqs/", text: "FAQ"}

 #- {permalink: "/volunteers/", text: "Volunteers"}
 #- {permalink: "/logistics/", text: "Logistics"}
 #- {permalink: "/hackathon/", text: "Hackathon"}



bottomNavigationLinks:
 - {link: "https://pyconfhyd.talkfunnel.com/2017/", text: "Register Here for Free"}
rightNavigationButtons:


# Hero Block
heroImage: "hero.jpg"
heroTitle: "Python In a Day for Women <typeout> "
eventDate: "October 7, 2017"
typeoutTextValues: '", Mumbai"'
typeoutFallback: ""
heroButtons:
 - {link: "https://docs.google.com/forms/d/e/1FAIpQLSe_T5_zZhcENRv2UWGHpRPfTix3SpYqb6JO2Ijcqp1tbNJMkg/viewform?c=0&w=1", text: "Register Here for Free"}
 

# About Block
aboutTitle: "Python In a Day for Women"
aboutBlock:
 - {title: "Meetup", image: "conference.png", text: "You’ll walk out of the meet up with Knowledge about the Python Ecosystem, Interesting conversations and possibly even lifelong friends." }
 - {title: "Workshops", image: "workshop.jpg", text: "Hands-on experience, hacking and debugging. Come and tame your favourite technology!" }
 #- {title: "Hackathon", image: "hackathon.jpg", text: "Full-day freestyle hackathon! Want some real team building on friday? Grab your team and join our hackathon!" }

# Statistic Block
#statisticBlockImage: "statistic.jpg"
#statisticBlock:
# - {count: "350", specialCharacter: "+", info: "attendees", detail: "from everywhere"}
# - {count: "48", specialCharacter: "+", info: "hours", detail: "of pure Google technologies"}
# - {count: "20", specialCharacter: "+", info: "speakers", detail: "from country and beyond"}
# - {count: "3", specialCharacter: "", info: "parallel tracks", detail: "plus entertainment lounge"}

# Latest News Block
#latestNewsTitle: "Latest news"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 3
rockstarSpeakersTitle: "Key-Note Speakers"
rockstarSpeakersButtonText: "See all speakers"

# Location Block
locationBlockTitle: "Location"
eventLocationName: "Conference Hall"
eventLocationLink: "https://www.iiit.ac.in/"
eventStreetAddress: "IIIT Hyderabad"
eventAddressLocality: "Hyderabad"
eventAddressLocalityRegion: "Telangana"
eventPostalCode: "500032"
eventAddressCountry: "India"
eventStartTime: "2017-10-07T09:30"
eventDoorTime: "09:00"
eventEndTime: "2017-10-08T17:00"
eventPlaceCoordinates: "17.4455415, 78.3471251"
mapCenterCoordinates: "17.4455415, 78.3471251"
mapMobileCenterCoordinates: "17.4455415, 78.3471251"
mapAPIkey: AIzaSyADHvpvQ4j0gpgqMjNp3h-QEc1N73Yp55Y

# Venue Block
#venueBlockTitle: "Venue"
#venueBigImage: "venue_0.jpg"
#venueSmallImage1: "venue_1.jpg"
#venueSmallImage2: "venue_2.jpg"
#venueSmallImage3: "venue_3.jpg"
#venueTitle: "Kinopalace Cinema"
#venueFeatures: ["3 huge cinema screens", "Doulby Digital Surround EX audio system", "Located directly in the city center"]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "PyConfHyd"
twitterFeed: "https://twitter.com/hydPython?c=10&cache_interval=8000"

# Partners Block
organizersTitle: "Sponsors"
partnersTitle: "Partners"
partnersC4sponsorsButton: "Become a sponsor"

# Subscribe Block
#subscribeImage: "subscribe.jpg"
#subscribeTitle: "Subscribe for updates"
#subscribeAction: "https://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
#subscribeInfo: "Registration will be open around end of August. Number of tickets are limited. Stay tuned!"

# Tickets Block
ticketsTitle: "Pricetable"
ticketsInfo: "Tickets grant access to all conference sections, coffee breaks and lunch. Accommodation is NOT included in the ticket price."
ticketsOffers:
 -
  name: "Workshop (Day 1)"
  price: "500"
  priceCurrency: "INR"
  ticketsNumber: "100"
  ribbon: "-20%"
  featured: true
  buyButtonLink: "https://in.explara.com/e/pyconf-hyderabad-2017/checkout"
  buyButtonText: "Buy Now"
  additionalInfo: "<a href='/schedule/#2017-10-07' target='_blank'>Workshop I / Workshop II</a>"
  ticketContentList: ["HydPy Conf Workshop tickets", "", ""]
  validFrom: "2017-08-10T10:00"
  validThrough: "2017-10-05T23:59"
  disabled: false
 -
  name: "Conference (Day 2)"
  price: "800"
  priceCurrency: "INR"
  ticketsNumber: "250"
  ribbon: "-20%"
  featured: true
  buyButtonLink: "https://in.explara.com/e/pyconf-hyderabad-2017/checkout"
  buyButtonText: "Buy Now"
  additionalInfo: "<a href='/schedule/#2017-10-08' target='_blank'>Conference Ticket</a><br/><br/>
                   Students Get 20% Discount - Apply Code <b>PYCONFSTUDENT2017</b>. Read the <a href='/faqs/' target='_blank'>FAQ</a> page for details.<br/><br/>"
  ticketContentList: ["HydPy Conf tickets", "", ""]
  validFrom: "2017-08-10T10:00"
  validThrough: "2017-10-05T23:59"
  disabled: false


# Footer
socialLinks:
 #- {link: "https://plus.google.com/b/102444623953913144164", icon: "google-plus"}
 #- {link: "https://twitter.com/hydPython", icon: "twitter"}
 
 - {link: "https://www.facebook.com/HydPy/", icon: "facebook"}
 - {link: "https://mail.python.org/mm3/mailman3/lists/hydpy.python.org/", icon: "email"}
 - {link: "https://twitter.com/hydPython", icon: "twitter"}
 # - {link: "https://www.meetup.com/Hyderabad-Python-Meetup-Group/", icon: "walking"}
 - {link: "https://github.com/HydPy/", icon: "github"}
 #- {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "http://hydpy.org", text: "Hydpy"}
   #- {link: "https://developers.google.com", text: "Google Developers"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:contact@hydpy.org", text: "contact@hydpy.org"}
 -
  title: "FAQ"
  links:
   - {link: "https://pyconfhyd.talkfunnel.com/2017/", text: "Call for Proposal"}
   - {permalink: "/volunteers/", text: "Volunteers"}
   - {permalink: "/coc/", text: "Code of Conduct"}

# Blog
#blogTitle: "Latest news"
#blogCommentsEnabled: true
#discusShortName: "devfestua"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "About us"
aboutUs: "<a href='http://www.hydpy.org'>Hyderabad Python User Group (HydPy)</a> is community driven group to promote Python in Hyderabad. HydPy has been conducting monthly Meetups & workshops in Hyderabad for last 2 years and it has over 4500 members. We work together with other communities in particular, python and in general Open Source Software (OSS) related groups within Hyderabad and the rest of India to further expand the usage and increase users of OSS. HydPy is a recognised regional community by <a href='https://pssi.org.in'>Python Software Society India (PSSI)</a> and <a href='https://www.python.org/psf/'>global Python Software Foundation (PSF)</a>. "

